### PR TITLE
Issue 96 omit commas

### PR DESCRIPTION
**Pull request by focusaurus**

### CODE REVIEW

**Comment by donpark** [comment]
Sorry but I think this feature needs to be optional, meaning via a CLI flag (maybe --noattrcomma), to maintain backward compatibility.

**Comment by focusaurus** [comment]
OK, I can add that. Not really sure backward compatibility is important for
a project like this. How many people are re-running html2jade over and over
again on the same inputs?  Anyway, I'll add it. Just wanted to mention that
I think the commas between attributes were due to some limitations in jade
TJ couldn't get around in early versions that have long since been solved
and they always seemed like a huge wart to me, so I was very pleased when
jade finally made them optional.

**Comment by donpark** [comment]
I went ahead and implemented the changes needed and released it as version 0.8.3 so I'll this close this PR but I do appreciate your help on this @focusaurus. Thanks. :-)

**Comment by donpark** [comment]
Re unnecessary commas, yeah. TJ was experimenting a bit. Not entirely happy with the result but it serves my needs.

**Pull request closed without merging**
